name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ekss3irsaaccess

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: prompt/actions-commit-hash@v2
      id: commit
      
    - uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag ekss3irsaaccess:${{ steps.commit.outputs.short }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ steps.commit.outputs.short }}

    
