name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: prompt/actions-commit-hash@v2
      id: commit
      
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ekss3irsaaccess:${{ steps.commit.outputs.short }}
    
    - name: Push the github image
      run: docker push ekss3irsaaccess:${{ steps.commit.outputs.short }}
