name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ekss3irsaaccess

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: prompt/actions-commit-hash@v2
      id: commit
      
    - uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3 
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ steps.commit.outputs.short }}
    
    - name: Set package visibility to public
      run: |
        gh api \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          /orgs/${{ github.repository_owner }}/packages/container/${{ env.IMAGE_NAME }}/visibility \
          -f visibility=public \
          -F package_type=container \
          -F repository=${{ github.repository }}
          -F visibility=public \
          -F package_type=container \
          -F repository=${{ github.repository }}


    
