name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ekss3irsaaccess

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: prompt/actions-commit-hash@v2
      id: commit
      
    - uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3 
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      run: |
        docker buildx build \
          --platform linux/arm64,linux/amd64 \
          --push \
          --tag ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.commit.outputs.commit_hash }} \
          .

    
